herbe: Make sure finished processes are treated as closed
When a herbe notification was right-clicked ("accepted" according to
the herbe readme), it signals that by exiting with exit status 2.

So far, we've only signalled that by emitting click_id to the bridge
(thus letting the website know about it being clicked), but we never
communicated that it was also closed by the same action.

When right-clicking a Discord notification, this meant that the
following happened:

- herbe exits with status 2
- We emit click_id, thus communicating to Discord that the notification
  was clicked.
- Discord calls .close() (in JS) on the notification.
- Our on_web_closed gets called and tries to send a SIGUSR1 to herbe to dismiss
  the notification.
- However, the herbe process already exited at this point, thus leading
  to:

  Traceback (most recent call last):
    File ".../qutebrowser/browser/webengine/notification.py", line 639, in on_web_closed
      os.kill(notification_id, signal.SIGUSR1)
  ProcessLookupError: [Errno 3] No such process

If we make it clear that the notification is already gone, and
on_web_closed does not seem to be called at all anymore.

(cherry picked from commit bd8ca51df4cea889e478393aab2b2d6f06ff1eb3)