Use string annotations for typing.Type
With Python 3.5.2 (which is shipped with Ubuntu 16.04), placing a typing.Type
into Union/Optional causes:

     TypeError: descriptor '__subclasses__' of 'type' object needs an argument

This was fixed in Python 3.5.3 via:
https://github.com/python/typing/issues/266

Fixes #5099