Adjust type hints
Fixes `AttributeError: partially initialized module 'qutebrowser.browser.browsertab' has no attribute 'AbstractTab' (most likely due to a circular import)`