Use qtutils.version_check to check for signal availability
With Qt 5.12 but an older PyQt, it looks like the attributes are available, but
connecting fails with:

    TypeError: C++ type 'QWebEngineClientCertificateSelection' is not supported
    as a signal argument type

Let's ensure we require both a new Qt and PyQt instead.