qt6: let importlib import PyQt6.sip
Currently, ":version" fails to show the sip version for Qt6. This is
because the sip module can't imported in the same way as Qt5. In Qt5,
the sip module can be imported after "from PyQt5.QtCore import *". In Qt
6, this is no longer the case,

    >>> from PyQt6.QtCore import *
    >>> import sip
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ModuleNotFoundError: No module named 'sip'

So let importlib import PyQt6.sip explicitly.