get_for_url: Handle empty urls.
When calling `config.instance.got(..., url=tab.url())` where the tab had
been initialised but hadn't navigated yet the passed url was `QUrl('')`
which was causing `qtutils.ensure_valid()` to throw an exception in
`urlmatch.matches()`. Stacktrace below:

      File "/home/user/projects/qutebrowser/qutebrowser/browser/browsertab.py", line 341, in set_default
        zoom = config.instance.get('zoom.default', url=self._tab.url())
      File "/home/user/projects/qutebrowser/qutebrowser/config/config.py", line 316, in get
        obj = self.get_obj(name, url=url)
      File "/home/user/projects/qutebrowser/qutebrowser/config/config.py", line 337, in get_obj
        value = self._values[name].get_for_url(url)
      File "/home/user/projects/qutebrowser/qutebrowser/config/configutils.py", line 160, in get_for_url
        if scoped.pattern is not None and scoped.pattern.matches(url):
      File "/home/user/projects/qutebrowser/qutebrowser/utils/urlmatch.py", line 278, in matches
        qtutils.ensure_valid(qurl)
      File "/home/user/projects/qutebrowser/qutebrowser/utils/qtutils.py", line 139, in ensure_valid
        raise QtValueError(obj)
    qutebrowser.utils.qtutils.QtValueError: PyQt5.QtCore.QUrl('') is not valid