Handle None in _toggle_sel_translate
This is the equivalent of the previous:

  TypeError: AbstractCaret.selection_toggled[bool].emit(): argument 1 has unexpected type 'NoneType'

When e.g. doing:

  qutebrowser --temp-basedir ':later 100 enter-mode caret' ':later 110 toggle-selection'

Handle this case and show an error instead of crashing.