Avoid module-level circular import
When running ua_fetch.py, websettings gets imported and fails:

    $ python3 scripts/dev/ua_fetch.py
    Traceback (most recent call last):
    File ".../scripts/dev/ua_fetch.py", line 16, in <module>
        import qutebrowser.config.websettings
    File ".../qutebrowser/config/websettings.py", line 32, in <module>
        from qutebrowser.config import config
    File ".../qutebrowser/config/config.py", line 31, in <module>
        from qutebrowser.config import configdata, configexc, configutils
    File ".../qutebrowser/config/configdata.py", line 32, in <module>
        from qutebrowser.config import configtypes
    File ".../qutebrowser/config/configtypes.py", line 65, in <module>
        from qutebrowser.utils import (standarddir, utils, qtutils, urlutils, urlmatch,
    File ".../qutebrowser/utils/standarddir.py", line 33, in <module>
        from qutebrowser.utils import log, debug, utils, version
    File ".../qutebrowser/utils/version.py", line 529, in <module>
        class WebEngineVersions:
    File ".../qutebrowser/utils/version.py", line 597, in WebEngineVersions
        def from_ua(cls, ua: websettings.UserAgent) -> 'WebEngineVersions':
    AttributeError: partially initialized module 'qutebrowser.config.websettings' has no attribute 'UserAgent' (most likely due to a circular import)