Stringify type to prevent import loop
This commit (aceef82b241e69a83ac) is on the main branch already, not
sure why this loop is only showing up on the tree tab branch. The stack
trace is:

    py311-pyqt67: commands[0]> .tox/py311-pyqt67/bin/python -bb -m pytest
    ImportError while loading conftest '/home/runner/work/qutebrowser/qutebrowser/tests/conftest.py'.
    tests/conftest.py:22: in <module>
        from helpers.fixtures import *  # noqa: F403
    tests/helpers/fixtures.py:29: in <module>
        import helpers.stubs as stubsmod
    tests/helpers/stubs.py:25: in <module>
        from qutebrowser.browser import browsertab, downloads
    qutebrowser/browser/browsertab.py:29: in <module>
        from qutebrowser.keyinput import modeman
    qutebrowser/keyinput/modeman.py:16: in <module>
        from qutebrowser.commands import runners
    qutebrowser/commands/runners.py:15: in <module>
        from qutebrowser.api import cmdutils
    qutebrowser/api/cmdutils.py:42: in <module>
        from qutebrowser.commands import command, cmdexc
    qutebrowser/commands/command.py:20: in <module>
        from qutebrowser.completion.models import completionmodel
    qutebrowser/completion/models/__init__.py:9: in <module>
        from qutebrowser.completion.models.util import DeleteFuncType
    qutebrowser/completion/models/util.py:11: in <module>
        from qutebrowser.config import config
    qutebrowser/config/config.py:15: in <module>
        from qutebrowser.commands import cmdexc, parser
    qutebrowser/commands/parser.py:16: in <module>
        class ParseResult:
    qutebrowser/commands/parser.py:20: in ParseResult
        cmd: command.Command
    E   AttributeError: partially initialized module 'qutebrowser.commands.command' has no attribute 'Command' (most likely due to a circular import)