Reland: Always make sure URLs for per-domain settings are valid
Before this commit, we failed a check further down if there was a pattern we
attempted to match:

  File ".../qutebrowser/config/configutils.py", line 236, in get_for_url
    if scoped.pattern is not None and scoped.pattern.matches(url):
  File ".../qutebrowser/utils/urlmatch.py", line 292, in matches
    qtutils.ensure_valid(qurl)
  File ".../qutebrowser/utils/qtutils.py", line 158, in ensure_valid
    raise QtValueError(obj)
  qutebrowser.utils.qtutils.QtValueError: PyQt5.QtCore.QUrl('') is not valid

(cherry picked from commit 8e92b29cda7c4d8df7ab0c6d304778c1824a7a35)

Fixes #5414