made the code less cryptic. and found a bug.
the bug that i found seems outside of my code. what makes me feel that
this is a bug, is that this crash only happens with `download-retry`.

the bug:
--------

    the command `:download-retry -a` (or any variant that causes
    multiple downloads to be retried), will cause qutebrowser to
    crash, if there are multiple failed downloads.

    to create multiple failed downloads, i simply used the command
    `:download lol` knowing that host `lol` doesn't exist. Similarly
    with host `haha`.

below is the crash message:
---------------------------

    01:11:00 ERROR: Download error: Host lol not found
    01:11:00 ERROR: Download error: Host haha not found
    01:11:04 ERROR: Uncaught exception
    Traceback (most recent call last):
      File "/home/caveman/torabora/dev/qutebrowser/qutebrowser/app.py", line 882, in eventFilter
        return handler(event)
      File "/home/caveman/torabora/dev/qutebrowser/qutebrowser/app.py", line 842, in _handle_key_event
        return man.eventFilter(event)
      File "/home/caveman/torabora/dev/qutebrowser/qutebrowser/keyinput/modeman.py", line 337, in eventFilter
        return self._eventFilter_keypress(event)
      File "/home/caveman/torabora/dev/qutebrowser/qutebrowser/keyinput/modeman.py", line 168, in _eventFilter_keypress
        handled = parser.handle(event)
      File "/home/caveman/torabora/dev/qutebrowser/qutebrowser/keyinput/basekeyparser.py", line 307, in handle
        handled = self._handle_special_key(e)
      File "/home/caveman/torabora/dev/qutebrowser/qutebrowser/keyinput/basekeyparser.py", line 136, in _handle_special_key
        self.execute(cmdstr, self.Type.special, count)
      File "/home/caveman/torabora/dev/qutebrowser/qutebrowser/keyinput/keyparser.py", line 44, in execute
        self._commandrunner.run(cmdstr, count)
      File "/home/caveman/torabora/dev/qutebrowser/qutebrowser/commands/runners.py", line 275, in run
        result.cmd.run(self._win_id, args, count=count)
      File "/home/caveman/torabora/dev/qutebrowser/qutebrowser/commands/command.py", line 525, in run
        self.handler(*posargs, **kwargs)
      File "/home/caveman/torabora/dev/qutebrowser/qutebrowser/mainwindow/prompt.py", line 372, in prompt_accept
        question.done()
      File "/home/caveman/torabora/dev/qutebrowser/qutebrowser/utils/usertypes.py", line 339, in done
        self.answered.emit(self.answer)
    RuntimeError: wrapped C/C++ object of type Question has been deleted