Only connect IPC after init has finished
Otherwise, if there's a fatal error message shown during init, we try to
open something via IPC before we're fully initialized. This can e.g.
lead to a KeyError for qtnetwork-download-manager:

    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/qutebrowser/app.py", line 120, in <lambda>
        process_pos_args(args, cwd=cwd, via_ipc=True,
      File "/usr/lib/python3/dist-packages/qutebrowser/app.py", line 230, in process_pos_args
        win_id = mainwindow.get_window(via_ipc, force_window=True)
      File "/usr/lib/python3/dist-packages/qutebrowser/mainwindow/mainwindow.py", line 89, in get_window
        window = MainWindow(private=None)
      File "/usr/lib/python3/dist-packages/qutebrowser/mainwindow/mainwindow.py", line 220, in __init__
        self._init_downloadmanager()
      File "/usr/lib/python3/dist-packages/qutebrowser/mainwindow/mainwindow.py", line 350, in _init_downloadmanager
        qtnetwork_download_manager = objreg.get('qtnetwork-download-manager')
      File "/usr/lib/python3/dist-packages/qutebrowser/utils/objreg.py", line 249, in get
        return reg[name]
      File "/usr/lib/python3.8/collections/__init__.py", line 1010, in __getitem__
        raise KeyError(key)
    KeyError: 'qtnetwork-download-manager'

(cherry picked from commit 6c0d8d59647b39ecf3292b125991522d3502db65)