config: Discard prior mutables before applying
If we only clear existing mutables *after* applying, we get into an
inconsistent state if there was an error in one of the config values:

The improper value lingers around in self._mutables, and then gets
returned when get_mutable_obj() (or update_mutables()) gets called the
next time.

Reproducer:

    qutebrowser --debug --temp-basedir \
        ':config-dict-add content.javascript.log_message.levels example.org bla' \
        ':later 1000 config-dict-add content.javascript.log_message.levels example.org bla'

Results in:

    ERROR: Invalid value 'bla' - expected a value of type list but got str.
    ERROR: example.org already exists in content.javascript.log_message - use --replace to overwrite!

Fixes the second part of #7343.

nb: As before, the mutable updating actually gets interrupted by a
failing update, instead of it e.g. collecting all errors but carrying
on. With this change, the remaining updates will thus also be discarded,
but that does not seem to be a problem with how mutables are currently
used. Ideally, we should get rid of the mutable handling entirely
anyways, at least for qutebrowser internal code - see #4344.